import json
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
OUT_DIR = BASE_DIR / "demo_outputs"
KG_PATH = OUT_DIR / "kg_graph.json"
TEMPLATE_PATH = BASE_DIR / "mai_t1d_knowledge_graph.html"
HTML_PATH = OUT_DIR / "kg_view.html"


def wrap_label(text: str, max_words_per_line: int = 2) -> str:
    words = [w for w in text.replace("_", " ").split() if w]
    if not words:
        return text
    lines = []
    for i in range(0, len(words), max_words_per_line):
        lines.append(" ".join(words[i : i + max_words_per_line]))
    return "\\n".join(lines)


def map_type(node_type: str) -> str:
    mapping = {
        "RawData": "RawData",
        "Pipeline": "QC",
        "IntermediateDataset": "AIReady",
        "Metadata": "Metadata",
        "DatasetCard": "DatasetCard",
        "Model": "ModelTraining",
        "TrainingActivity": "ModelTraining",
        "ModelCard": "ModelCard",
        "EvaluationMetrics": "Registry",
        "Agent": "Registry",
    }
    return mapping.get(node_type, "Registry")


def map_edge_label(relation: str) -> str:
    mapping = {
        "USED": "used",
        "WAS_GENERATED_BY": "was generated by",
        "WAS_DERIVED_FROM": "was derived from",
        "WAS_DOCUMENTED_BY": "documentedBy",
        "LINKED_TO": "linkedTo",
        "WAS_ATTRIBUTED_TO": "attributedTo",
    }
    return mapping.get(relation, relation.lower())


def stringify_detail(node: dict) -> dict:
    detail = {}
    for k, v in node.items():
        if k in {"id", "type"}:
            continue
        if isinstance(v, (dict, list)):
            detail[k] = json.dumps(v, ensure_ascii=False)
        else:
            detail[k] = str(v)
    if not detail:
        detail["info"] = "N/A"
    return detail


def convert_graph(graph: dict):
    nodes_out = []
    for n in graph.get("nodes", []):
        raw_id = n.get("id", "")
        short_id = raw_id.split(":", 1)[1] if ":" in raw_id else raw_id
        label = wrap_label(short_id, max_words_per_line=2)
        nodes_out.append(
            {
                "id": short_id,
                "label": label,
                "type": map_type(n.get("type", "Registry")),
                "detail": stringify_detail(n),
            }
        )

    edges_out = []
    for e in graph.get("edges", []):
        source = e.get("source", "")
        target = e.get("target", "")
        source_id = source.split(":", 1)[1] if ":" in source else source
        target_id = target.split(":", 1)[1] if ":" in target else target
        edges_out.append(
            {
                "source": source_id,
                "target": target_id,
                "label": map_edge_label(e.get("relation", "")),
            }
        )
    return nodes_out, edges_out


def replace_const_array(html: str, const_name: str, data_obj) -> str:
    start_token = f"const {const_name} = ["
    start_idx = html.find(start_token)
    if start_idx == -1:
        raise ValueError(f"Cannot find const {const_name} in template")
    end_idx = html.find("];", start_idx)
    if end_idx == -1:
        raise ValueError(f"Cannot find end of const {const_name} in template")

    replacement = f"const {const_name} = {json.dumps(data_obj, ensure_ascii=False, indent=6)};"
    return html[:start_idx] + replacement + html[end_idx + 2 :]


def main() -> None:
    if not KG_PATH.exists():
        raise FileNotFoundError(f"Missing KG file: {KG_PATH}")
    if not TEMPLATE_PATH.exists():
        raise FileNotFoundError(f"Missing template HTML: {TEMPLATE_PATH}")

    graph = json.loads(KG_PATH.read_text(encoding="utf-8"))
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    nodes, edges = convert_graph(graph)

    rendered = replace_const_array(template, "NODES", nodes)
    rendered = replace_const_array(rendered, "EDGES", edges)

    HTML_PATH.write_text(rendered, encoding="utf-8")
    print(f"[render] Template UI HTML generated: {HTML_PATH}")


if __name__ == "__main__":
    main()
